name: Hosting

on:
  push:
    branches: [main]

jobs:
  asciidoctor_job:
    runs-on: ubuntu-latest
    name: Build AsciiDoctor
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Markdown To HTML
        uses: docker://pandoc/core:2.9
        with:
          args: -f markdown -t html 'index.md' > 'index.html'
      - name: Publish to AWS S3 & CloudFront Cache Clear
        uses: opspresso/action-s3-sync@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          FROM_PATH: '.'
          DEST_PATH: ${{ secrets.AWS_S3_BUCKET_PATH }}
